services:
  # ===== DATOS: una base por servicio, cada una en su propia red =====
  backend-db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root123
    volumes:
      - backend_db_data:/var/lib/mysql
      - ./backend-db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [datos-backend]
    # Sin "ports": no se expone fuera de Docker

  auth-db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root123
    volumes:
      - auth_db_data:/var/lib/mysql
      - ./auth-db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [datos-auth]

  # ===== SERVICIOS =====
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DB_HOST: backend-db
      DB_PORT: 3306
      DB_NAME: operacion
      DB_USER: backend_user
      DB_PASSWORD: backend_pass
      PORT: 4000
      JWKS_URL: http://auth-service:5001/auth/jwks   # por la red "interna"
      JWT_ISSUER: ce5508-auth-service
      JWT_AUDIENCE: ce5508-backend
    ports:
      - "4000:4000"
    depends_on:
      backend-db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks: [interna, datos-backend]

  auth-service:
    build: ./auth-service
    restart: unless-stopped
    environment:
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_NAME: auth
      DB_USER: auth_user
      DB_PASSWORD: auth_pass
      PORT: 5001
      KEYS_DIR: /keys
      JWT_ISSUER: ce5508-auth-service
      JWT_AUDIENCE: ce5508-backend
      ACCESS_TTL_MIN: 15
      REFRESH_TTL_H: 8
    ports:
      - "5001:5001"
    depends_on:
      auth-db:
        condition: service_healthy
    volumes:
      - ./auth-service:/app
      - auth_keys:/keys        # clave PRIVADA: se monta SOLO aqui
    networks: [interna, datos-auth]

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:4000
      VITE_AUTH_URL: http://localhost:5001
    ports:
      - "5173:5173"
    depends_on: [backend, auth-service]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks: [borde]

# Redes: cada servicio solo alcanza lo que necesita.
networks:
  borde:          # navegador <-> gateway (el gateway llega en el paso 5)
  interna:        # gateway <-> servicios
  datos-auth:     # SOLO auth-service <-> auth-db
  datos-backend:  # SOLO backend <-> backend-db

volumes:
  backend_db_data:
  auth_db_data:
  auth_keys: